camera:
  width: 1280
  height: 720
  device_index: 1
  exposure: -6
  wb_temperature: 4600

arena:
  x_start_m: -0.010812152843194799
  x_end_m: 0.46
  y_start_m: -0.19926
  y_end_m: -0.32166

robot:
  xmlrpc_port: 50000
  rest_pose: [0.100, 2.28, -2.161, 0.0, 0.0, 0.0]
  q_max_rad_s: 0.5585               # 32 deg/s
  accel_rad_s2: 1.7453              # 100 deg/s^2
  measured_latency_s: 0.064

prediction:
  model: kalman
  prediction_length: 150
  history_length: 60
  fps: 25.223
  max_uncertainty: 9999999990.0
  linear_smooth_frames: 60
  occlusions_enabled: false
  kf_centre_mode: false
  kf_process_sigma: 12.0
  kf_sensor_sigma: 3.0

interception:
  min_time_s: 2.0
  max_time_s: 99.0
  grad_threshold: 0.50
  short_error_window: 100

runtime:
  simulation: false
  send_xmlrpc: true
  debug: false
  save_video: false
  real_speed: true
  color_filter: blue
